# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run cmake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../math

      - name: Run build
        run: cd build && cmake --build . --config Release
        
      - name: Run test
        run: build/Release/TestMath.exe
